name: LEKSHMIKRISHNA K M
 avatar: /path/to/your/avatar
 bio: Welcome to my GitHub portfolio! I am a recent graduate with a degree in Computer Science and Engineering from the College of Engineering and Management Punnapra, affiliated with APJ Abdul Kalam Technological University. I am passionate about leveraging technology to solve real-world problems.
 email: your.email@example.com
 location: Kallath Thuravoor po Cherthala, Alappuzha
